# Generated by Django 4.0.6 on 2022-08-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre ')),
                ('descriptions', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción ')),
                ('bar_code', models.TextField(unique=True, verbose_name='Código de barras')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Precio ')),
                ('price_max', models.FloatField(blank=True, null=True, verbose_name='Precio máximo: ')),
                ('price_min', models.FloatField(blank=True, null=True, verbose_name='Precio mínimo ')),
                ('stock', models.PositiveIntegerField(verbose_name='Existencias')),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d', verbose_name='Imágenes')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ModelPuntoDeVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre ')),
                ('addres', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección ')),
                ('productos', models.ManyToManyField(to='PuntoDeVenta.modelproducto')),
            ],
            options={
                'verbose_name': 'Punto de venta',
                'verbose_name_plural': 'Puntos de venta',
            },
        ),
    ]
