# Generated by Django 4.0.6 on 2022-09-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoDeVenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproducto',
            name='exist',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Existencia'),
        ),
        migrations.AlterField(
            model_name='modelproducto',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
    ]
