# Generated by Django 4.0.6 on 2022-08-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='movil',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
    ]
